services:
  tracing:
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
  database: 
    image: quizler/database
    build: services/database
    ports: 
      - 5432:5432
    env_file: .env
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  main-node:
    image: quizler/main-node
    build: services/main-node