services:
  tracing-ui:
    image: quizler/tracing-ui
    build:
      context: services/tracing
      dockerfile: query.Dockerfile
    env_file: .env
    ports: 
      - 16686:16686
  tracing-collector:
    image: quilzer/tracing-collector
    build: 
      context: services/tracing
      dockerfile: collector.Dockerfile
    env_file: .env
    ports: 
      - 4317:4317
      - 4318:4318
      - 14269:14269
  database: 
    image: quizler/database
    build: services/database
    ports: 
      - 5432:5432
    env_file: .env
  main-node:
    image: quizler/main-node
    build: services/main-node