services:
  # Tracing service
  tracing:
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
  # Database
  database: 
    image: quizler/database
    build: services/database
    ports: 
      - 5432:5432
    env_file: .env
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  # Main api node
  main-node:
    image: quizler/main-node
    build: services/main-node
  # SMTP Mailing service
  mail:
    image: 'mailhog/mailhog'
    ports:
      # SMTP
      - 1025:1025
      # HTTP
      - 8025:8025