[package]
name = "main-node"
version = "0.1.0"
edition = "2021"

[dependencies]
# Async runtime
tokio.workspace = true

# Tracing & Logging
tracing.workspace = true
tracing-subscriber.workspace = true
log-panics.workspace = true

# Tracing OpenTelemetry
opentelemetry.workspace = true
tracing-opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-otlp.workspace = true

axum.workspace = true
tower.workspace = true
tower-http.workspace = true

dotenvy.workspace = true

thiserror.workspace = true
anyhow.workspace = true
